name: simple_chat_demo
description: "Simple Chat Demo Application"
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  iconsax_plus: ^1.0.0
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.6.0
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.1
  responsive_builder: ^0.7.1
  flutter_screenutil: ^5.9.3
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  camera: ^0.11.2
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.3
  speech_to_text: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_gen:
  output: lib/gen/ 
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/

